### ISSUE TITLE
Problem with fullscreen.

### ISSUE THREAD

**Issue by Auri-Chan** [Lootyhoof/pmchrome#1]
I love the theme, specially how it handles the tabs bar and makes it really compact, however, everytime I'm watching youtube, or any other HTML5 video player and turn it to fullscreen, a white bar appears at the top of the screen. Hoping this can be fixed soon, I'd hate to stop using this theme over that...

![ss 2015-08-19 at 10 48 58](https://cloud.githubusercontent.com/assets/13876786/9370009/0816ad5a-46c5-11e5-871c-ce1f5f142821.png)

**Comment by Lootyhoof** [comment]
Odd; this works for me just fine. What OS and Pale Moon version are you using?

![Fullscreen Video](http://i.imgur.com/8JgOWs6.jpg)

**Comment by Auri-Chan** [comment]
Windows 7, Pale Moon v.25.6.0 (x86), have tabs on top option enabled and when I turn that option off, the bar is gone, so I assume the problem has something to do with that.

If I right-click that white bar this is what appears, thought it might help identifying the issue.
![ss 2015-08-20 at 05 16 17](https://cloud.githubusercontent.com/assets/13876786/9375611/b71335c8-46fa-11e5-83e0-c04ff7f3d8e3.png)

**Comment by Lootyhoof** [comment]
Fixed in 38f278d. I'll get v1.1.1 out soon with the fix. Thanks for the report!

**Comment by Auri-Chan** [comment]
Completely fixed, thanks a lot!
