### ISSUE TITLE
[FIXED] Palemoon 27 incompatibility

### ISSUE THREAD

**Issue by sergeevabc** [Lootyhoof/pmchrome#2]
![Visual weirdness](http://i.imgur.com/9zweoQm.png)

Could you be so kind to fix it?

**Comment by Lootyhoof** [comment]
Already fixed as of https://github.com/Lootyhoof/pmchrome/commit/2b4464506c41bb9de890fb3ac21315ee9e3456d1, a full release will come soon.

**Comment by sergeevabc** [comment]
@Lootyhoof How soon? Development of [Duke Nukem Forever](https://en.wikipedia.org/wiki/Development_of_Duke_Nukem_Forever) took 15 years, for example.
