### ISSUE TITLE
[FIXED] Make compatible with Developer Tools

### ISSUE THREAD

**Issue by sergeevabc** [Lootyhoof/pmchrome#3]
PM [27.0.2][1] re-introduced Developer Tools.
But it [looks ugly][2] without proper theme support.

[1]: http://www.palemoon.org/releasenotes.shtml
[2]: https://i.imgur.com/4auGCEC.png

**Comment by Lootyhoof** [comment]
Already fixed as of https://github.com/Lootyhoof/pmchrome/commit/e4b1529e6f5c9b87d2179f2928c4368b264d751a, an update will be released soon.
