### ISSUE TITLE
browser.display.standalone_images.background_color ignored

### ISSUE THREAD

**Issue by Montclair** [Lootyhoof/pmchrome#5]
browser.display.standalone_images.background_color setting is ignored. Once the theme is disabled, it's properly recognized. Any chance of fixing that as I love the theme, but hate the default dark gray background when viewing images standalone?

**Comment by Lootyhoof** [comment]
Thanks, I'll take a look at this soon.

**Comment by Lootyhoof** [comment]
Sorry for the delay. This has been dealt with in 1e41b65 and will be out for release soon (in addition to Pale Moon v28 fixes).

Thanks!
