### ISSUE TITLE
[FIXED] Palemoon 28 incompatibility

### ISSUE THREAD

**Issue by sergeevabc** [Lootyhoof/pmchrome#6]
Dear Ryan, I see you’ve already updated Dark/White Moon themes to support 28.* features.
Alas, I prefer PMChrome, so could you tell if there are plans to update it as well?

**Comment by Lootyhoof** [comment]
This has already been added in https://github.com/Lootyhoof/pmchrome/commit/de9870245e0e43e3ef72fa27510e77ab3466eaf6 and will be released soon.

Thanks!
