### ISSUE TITLE
[FIXED] New tab button is missing

### ISSUE THREAD

**Issue by sergeevabc** [Lootyhoof/pmchrome#7]
Expected
![](https://addons.palemoon.org/datastore/addons/pmchrome/preview.png)

Actual
![](http://images.vfl.ru/ii/1535900723/c949a75f/23159835.png)

Dear @Lootyhoof,
for unknown reason I do not see a new tab button next to the opened tabs, why?

PM 28.0.1 x64
PMChrome 4.3.0

**Comment by Lootyhoof** [comment]
What OS are you using? I don't see a problem on Windows 10:

![New tab](https://i.imgur.com/4KnJ6A4.png)

Have you dragged it off the window perhaps? Is it in your Customize window?

**Comment by sergeevabc** [comment]
Going to Customize window and restoring the default set did the trick, thank you.
