### ISSUE TITLE
Would it be possible to update pmchrome to more closely match googles newer material design theme?

### ISSUE THREAD

**Issue by jazir555** [Lootyhoof/pmchrome#9]
![chrome material design](https://user-images.githubusercontent.com/31750063/52921530-e5b3e500-32cc-11e9-98fc-5a3c6ac4af9e.PNG)

This is chrome's current design.

This is the current design of Palemoon with PMChrome:
![pale moon](https://user-images.githubusercontent.com/31750063/52921536-f7958800-32cc-11e9-90ab-1b2b5c7d60c9.PNG)

Would it be possible make it more closely match google's newer theme? Pale moon still looks like it's stuck in the mid-2000's. I appreciate your hard work. Thanks for responding

**Comment by Lootyhoof** [comment]
You should use the fork instead: https://github.com/FranklinDM/MaterialMoon

This version is for the pre-material Chrome style.
